### ISSUE TITLE
Generalize the lifecycle statement standard from stat software review?

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#366]
Cc @mpadge, @jooolia 

Should all submissions include a lifecycle statement.

**Comment by mpadge** [comment]
My opinion: A lifecycle statement provides extremely useful information that is not otherwise conveyed at all, and I would love for it to be considered essential. But ... this really is a very different kind of information that has no direct place in a code repository. We stat-software folk went through very protracted wrangling of lots of different approaches, and ultimately settled on the path-of-least-resistance of requiring such a statement and *encouraging* but not requiring it to be in the `CONTRIBUTING.md` file.

Given that, my suggestion would actually be first to improve advice and help for authors on the general form of `CONTRIBUTING.md` files. Current [package guide chapter](https://devguide.ropensci.org/authors-guide.html) makes no mention of requiring such a file, yet the [contributing guide chapter](https://devguide.ropensci.org/collaboration.html#contributing-guide) states:

> Having a contributing file as .github/CONTRIBUTING.md or docs/CONTRIBUTING.md is compulsory.

Presence of these files is also [checked by `pkgcheck`](https://github.com/ropensci-review-tools/pkgcheck/blob/main/R/check-has-contrib.R), and use of `pkgcheck` is now recommended [at the outset of the "Guide for Authors" chapter](https://devguide.ropensci.org/authors-guide.html).

I think we first need some clarity about what is actually required in general, perhaps in the form of a simple list of all the things which `pkgcheck` will object to if they're not present. I think a slight re-structure of Chapter 6 (Guide for Authors) might be called for here? Within that, we could then include a brief statement on the requirement of a `CONTRIBUTING.md` file, for which I also think we should have a more useful reference or two than current link to  [this gist template](https://gist.github.com/peterdesmet/e90a1b0dc17af6c12daf6e8b2f044e7c), which I suspect might often be counter-productive through being too long and convoluted. 

... Finally, once all that has been addressed, then I think, yes, we could also extend that by indicating that we require some kind of lifecycle statement along the lines of the [General Stats Standard G1.2](https://stats-devguide.ropensci.org/standards.html#documentation).

**Comment by mpadge** [comment]
## TODO

- [ ] Revise [Dev Guide Chapter 6: *Guide for Authors*](https://devguide.ropensci.org/authors-guide.html) by structuring in sub-sections to improve clarity and flow
- [ ] Move the entire section on `CONTRIBUTING.md` files from current location in [Chapter 10: *Collaboration Guide*](https://devguide.ropensci.org/collaboration.html#contributing-guide) to Author's Guide in Chapter 6.
- [ ] Draft a template `CONTRIBUTING.md` guide for general use, or maybe even better and simpler, recommend `usethis::use_tidy_contributing()` and clarify that people are free to modify however they like (under CoC guidelines).
- [ ] Extend description of CONTRIBUTING requirements (or at least suggestions) to include a lifecycle statement.

**Comment by maelle** [comment]
Also related: #334

**Comment by mpadge** [comment]
Good link - thanks! Now that so much of the previously semi-random bag of requirements is auto-done via `pgkcheck`, the actual *Guide for Authors* chapter can actually be streamlined quite a bit, and lots of things shucked off to some kind of "what, how, and why of `pkgcheck`" appendix or sub-section or something. That links has lots of good thoughts for that.

**Comment by noamross** [comment]
Commenting now after talk with Mark.  After completion of >=2 stats packages, let's put together a proposal of new general standards we're considering migrating to all packages, for consideration by editors.

**Comment by maelle** [comment]
@mpadge this is related to #391 isn't it? :smile_cat:

**Comment by mpadge** [comment]
Yes, indeed, and can likely be closed because that effectively covers the main concerns here, except the bits about explicit descriptions in a CONTRIBUTING file. @maelle Do you think that's still necessary, or do you think the new working via #391 suffice?

**Comment by maelle** [comment]
>  except the bits about explicit descriptions in a CONTRIBUTING file

Yes that could still be useful?

**Comment by jooolia** [comment]
Sorry just having a look at this now, do we have good examples of lifecycle statements? I have some ideas in my head, but I am wondering if we do see these statements in the wild? :)
