### ISSUE TITLE
Version 0.8.0 pre-release checklist

### ISSUE THREAD

**Issue by mpadge** [ropensci/dev_guide#448]
### Current issues assigned to @mpadge or v0.8.0 milestone

- [x] 446: [Add other mention of stat software review](https://github.com/ropensci/dev_guide/issues/446)
- [x] 445: [Move scripts to {devguider}](https://github.com/ropensci/dev_guide/issues/445)
- [x] 442: [Make script to open pre-release issue](https://github.com/ropensci/dev_guide/issues/442)
- [x] 388: [Acknowledgement of authorship / contributors](https://github.com/ropensci/dev_guide/issues/388)
- [x] 382: [Recommend pkgcheck GitHub Action?](https://github.com/ropensci/dev_guide/issues/382)
- [x] 366: [Generalize the lifecycle statement standard from stat software review?](https://github.com/ropensci/dev_guide/issues/366)
- [x] 334: [Add contributing guide standards as a separate chapter](https://github.com/ropensci/dev_guide/issues/334)
- [x] 438: [Improve archival guidance (rename README, have super small README)](https://github.com/ropensci/dev_guide/issues/438)
- [x] 356: [Add check command to author and reviewer guides once it is possible](https://github.com/ropensci/dev_guide/issues/356)
- [x] 355: [Document finalize transfer command when ready](https://github.com/ropensci/dev_guide/issues/355)
- [x] 344: [Improve PDF output](https://github.com/ropensci/dev_guide/issues/344)
- [x] 463: [update pre-release checklist links to devguider](https://github.com/ropensci/dev_guide/issues/463)

### Repo maintenance between releases

- [x] Look at the issue tracker for [the dev guide](https://github.com/ropensci/dev_guide/issues) and for [software review meta](https://github.com/ropensci/software-review-meta/issues) for changes still to be made in the dev guide. Assign dev guide issues to milestones corresponding to versions, either the next one or the one after that, e.g. [version 0.3.0](https://github.com/ropensci/dev_guide/milestone/2). Encourage PRs, have them reviewed.

### 1 month prior to release

- [x] Remind editors to open issues/PRs for items they want to see in the next version.

- [x] Ask editors for any feedback you need from them before release.

- [x] For each contribution/change make sure the NEWS in Appendix.Rmd were updated.

- [x] Plan a date for release in communication with `@stefaniebutland` who will give you a date for publishing a blog post / tech note.

### 2 weeks prior to release

- [x] Draft a blog post / tech note about the release with enough advance for editors and then Stef to review it (2 weeks). [Example](https://github.com/ropensci/roweb2/pull/452), [General blog post instructions](https://github.com/ropensci/roweb2#contributing-a-blog-post), [specific instructions for release posts](#releaseblogpost). 

- [x] Make a PR from the dev branch to the master branch, ping editors on GitHub and Slack. Mention the blog post draft in a comment on this PR.

### Release

- [x] Check URLs using [the corresponding script](https://github.com/ropensci/dev_guide/blob/master/inst/book_grooming.R).

- [x] [Spell check](https://github.com/ropensci/dev_guide/blob/master/inst/spelling-check.R). Update the [WORDLIST](https://github.com/ropensci/dev_guide/blob/master/inst/WORDLIST) as necessary.

- [x] Squash and merge the PR from dev to master.

- [x] GitHub release, check Zenodo release.

- [x] Re-build (for Zenodo metadata update in the book) or wait for daily build

- [x] Re-create the dev branch

- [x] Finish your blog post / tech note PR. Underline the most important aspects to be highlighted in tweets as part of the PR discussion.

**Comment by maelle** [comment]
@mpadge shouldn't this issue be assigned to the version milestone by the script?

**Comment by maelle** [comment]
@mpadge could you please check the last boxes and close? :smile_cat:
